Rails.application.routes.draw do
  get "/" => "home#top"
  get "/login" => "universities#login_form"
  get "/players/index" =>"players#index"
  get "/reg/top" => "universities#top"
  post "/login" => "universities#login"
  post "/logout" => "universities#logout"
  post "/players/add" => "players#add"
  post "/players/destroy/:id" => "players#destroy"
  get "/players/edit/:id" => "players#edit"
  post "/players/update/:id" => "players#update"
  get '/entries/index' => "entries#index"
  post "/entries/add" => "entries#add"
  post "/entries/destroy/:id" => "entries#destroy"
  get "/pairs/index" => "pairs#index"
  post "/pairs/add/:id" => "pairs#add"
  post "/pairs/addtwo/:id" => "pairs#addtwo"
  post "/pairs/destroy/:id" => "pairs#destroy"
  post "/pairs/destroytwo/:id" => "pairs#destroytwo"
  get 'fours/index' => "fours#index"
  post "fours/add" => "fours#add"
  post "fours/destroy/:id" => "fours#destroy"
  get "/reg/confirm" => "universities#confirm"
  get "/reg/choice" => "universities#choice_tour_form"
  post "/choice" => "universities#choice"

  get "operations/top" => "operations#top"
  get "operations/login" => "operators#login_form"
  post "operations/login" => "operators#login"
  get "operators/index" => "operators#index"
  get "operators/edit/:id" => "operators#edit"
  post "operators/update/:id" => "operators#update"
  post "operations/logout" => "operators#logout"
  get "operations/accounts/index" => "operations#accounts_index"
  post "operations/accounts/add" => "operations#accounts_add"
  get "operations/accounts/edit/:id" => "operations#accounts_edit"
  post "operations/accounts/update/:id" => "operations#accounts_update"
  post "operations/accounts/destroy/:id" => "operations#accounts_destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
