# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Operation.create!( id: 1, command : "1")
Operation.create!( id: 2, command : "6")
Operation.create!( id: 3, command : "9")
Operation.create!( id: 4, command : "00")
Operation.create!( id: 5, command : "00")
Operation.create!( id: 6, command : "6")
Operation.create!( id: 7, command : "7")
Operation.create!( id: 8, command : "10")
Operation.create!( id: 9, command : "10")
Operation.create!( id: 10, command : "6")
Operation.create!( id: 11, command : "9")
Operation.create!( id: 12, command : "00")
Operation.create!( id: 13, command : "00")
Operation.create!( id: 14, command : "7")
Operation.create!( id: 15, command : "14")
Operation.create!( id: 16, command : "00")
Operation.create!( id: 17, command : "00")
Operation.create!( id: 18, command : "7")
Operation.create!( id: 19, command : "6")
Operation.create!( id: 20, command : "00")
Operation.create!( id: 21, command : "00")
Operation.create!( id: 22, command : "7")
Operation.create!( id: 23, command : "5")
Operation.create!( id: 24, command : "00")
Operation.create!( id: 25, command : "00")
Operation.create!( id: 26, command : "1")
Operation.create!( id: 27, command : "8")
Operation.create!( id: 28, command : "14")
Operation.create!( id: 29, command : "14")
Operation.create!( id: 30, command : "00")
Operation.create!( id: 31, command : "8")
Operation.create!( id: 32, command : "14")
Operation.create!( id: 33, command : "20")
Operation.create!( id: 34, command : "00")

Operator.create!( id:1, name: "admin", password: "password")
Operator.create!( id:2, name: "zennihon_admin", password: "password")
Operator.create!( id:3, name: "kansai_admin", password: "password")
Operator.create!( id:4, name: "kantou_admin", password: "password")
Operator.create!( id:5, name: "zennihon_staff", password: "password")
Operator.create!( id:6, name: "kansai_staff", password: "password")
Operator.create!( id:7, name: "kantou_staff", password: "password")
